// Banca dati domande — Quizzone di Roma Antica & Fossacava
// Struttura: QUESTIONS[livello][modalita] = [ ...domande ]
// livello: junior (10-13), medio (14-16), senior (17-18)
// modalita: multipla, vf, immagine

const QUESTIONS = {

  junior: {
    multipla: [
      { q: "Chi sono, secondo la leggenda, i fondatori di Roma?", options: ["Romolo e Remo", "Enea e Latino", "Giulio Cesare e Augusto", "Bruto e Cassio"], answer: 0,
        info: "Secondo il mito, Romolo fondò Roma il 21 aprile 753 a.C. dopo aver litigato con il fratello Remo." },
      { q: "Da quale animale furono allattati Romolo e Remo, secondo il mito?", options: ["Una lupa", "Un'aquila", "Un cinghiale", "Una capra"], answer: 0,
        info: "La lupa capitolina è uno dei simboli più famosi di Roma." },
      { q: "Su quanti colli sorge Roma secondo la tradizione?", options: ["Cinque", "Sette", "Nove", "Dodici"], answer: 1,
        info: "I sette colli sono: Palatino, Campidoglio, Quirinale, Viminale, Esquilino, Celio e Aventino." },
      { q: "Come si chiama il grande anfiteatro di Roma dove si svolgevano i combattimenti dei gladiatori?", options: ["Pantheon", "Colosseo", "Circo Massimo", "Foro Romano"], answer: 1,
        info: "Il Colosseo (Anfiteatro Flavio) poteva ospitare decine di migliaia di spettatori." },
      { q: "Chi era Giulio Cesare?", options: ["Un console e generale romano", "Un re etrusco", "Un dio romano", "Un gladiatore"], answer: 0,
        info: "Cesare fu un abilissimo generale e uomo politico, protagonista della tarda Repubblica romana." },
      { q: "Come si chiamava il primo imperatore di Roma?", options: ["Nerone", "Augusto", "Traiano", "Romolo"], answer: 1,
        info: "Augusto (Ottaviano) divenne il primo imperatore nel 27 a.C., dando inizio all'Impero Romano." },
      { q: "Che cos'è una legione?", options: ["Un'unità dell'esercito romano", "Un tipo di tempio", "Una moneta romana", "Un tribunale"], answer: 0,
        info: "Una legione romana era composta da migliaia di soldati, i legionari." },
      { q: "Con quale materiale i romani costruivano le loro famose strade?", options: ["Legno", "Pietra e ghiaia", "Mattoni crudi", "Sabbia"], answer: 1,
        info: "Le strade romane, come la Via Appia, erano costruite con strati di pietra e duravano secoli." },
      { q: "Chi erano i gladiatori?", options: ["Sacerdoti del tempio", "Combattenti che si sfidavano nell'arena", "Soldati a cavallo", "Senatori anziani"], answer: 1,
        info: "I gladiatori si esibivano in combattimenti spettacolari per intrattenere il pubblico romano." },
      { q: "Qual è il nome del marmo pregiato estratto vicino a Carrara, usato anche a Roma?", options: ["Marmo lunense", "Marmo etrusco", "Marmo greco", "Marmo egizio"], answer: 0,
        info: "Il marmo delle Alpi Apuane era chiamato 'lunense' dal nome della colonia romana di Luni, da cui veniva esportato." }
    ],
    vf: [
      { q: "I romani costruivano acquedotti per portare l'acqua nelle città.", answer: true,
        info: "Gli acquedotti romani erano vere e proprie opere di ingegneria, capaci di trasportare acqua per decine di chilometri." },
      { q: "Il Colosseo si trova ad Atene.", answer: false,
        info: "Il Colosseo si trova a Roma, in Italia." },
      { q: "Annibale attraversò le Alpi con gli elefanti per attaccare Roma.", answer: true,
        info: "Il generale cartaginese Annibale compì questa impresa durante la Seconda Guerra Punica." },
      { q: "I gladiatori combattevano sempre e solo contro i leoni.", answer: false,
        info: "I gladiatori combattevano soprattutto tra loro; gli animali erano protagonisti di altri spettacoli, le venationes." },
      { q: "Roma fu fondata, secondo la leggenda, nel 753 a.C.", answer: true,
        info: "Questa è la data tradizionale della fondazione di Roma, tramandata dagli antichi storici romani." },
      { q: "L'imperatore Augusto era il nipote adottivo di Giulio Cesare.", answer: true,
        info: "Cesare adottò Ottaviano (futuro Augusto) come figlio nel suo testamento." },
      { q: "L'antica Roma fu governata solo da re e non ebbe mai una repubblica.", answer: false,
        info: "Dopo la cacciata dell'ultimo re, Roma fu una Repubblica per quasi 500 anni, prima di diventare un Impero." },
      { q: "Fossacava è un'antica cava romana di marmo vicino a Carrara.", answer: true,
        info: "Fossacava, lungo la strada per Colonnata, è uno dei siti estrattivi romani meglio conservati d'Italia." },
      { q: "A Fossacava lavoravano solo uomini liberi, mai schiavi.", answer: false,
        info: "Nelle cave lavoravano soprattutto schiavi, spesso di origine orientale, insieme a liberti e capicantiere liberi." },
      { q: "Il Circo Massimo era usato per le corse dei carri.", answer: true,
        info: "Il Circo Massimo era il più grande stadio di Roma, dedicato alle corse delle bighe e delle quadrighe." }
    ],
    immagine: [
      { img: "assets/img/fossacava_ingresso.jpg", q: "Cosa indica questo cartello?", options: ["L'ingresso di una cava romana di marmo", "L'ingresso di un museo egizio"], answer: 0,
        info: "Il cartello segnala l'ingresso di Fossacava, la Cava Romana del I secolo a.C. vicino a Carrara." },
      { img: "assets/img/strumenti_estrazione_marmo.jpg", q: "Che cosa vedi in questa immagine?", options: ["Antichi strumenti di ferro per lavorare il marmo", "Posate da cucina romane"], answer: 0,
        info: "Piccone, mazza e piattine (cunei) erano gli attrezzi usati dai cavatori romani per staccare i blocchi." },
      { img: "assets/img/labra.jpg", q: "Che cos'è questo grande oggetto di marmo?", options: ["Una vasca romana (labrum) per fontane e terme", "Uno scudo da gladiatore"], answer: 0,
        info: "Il labrum era una grande vasca usata in terme, fontane e ninfei romani." },
      { img: "assets/img/anfiteatro_luni.jpg", q: "Cosa mostra questa foto scattata dall'alto?", options: ["Le rovine di un anfiteatro romano", "Un campo da calcio moderno"], answer: 0,
        info: "È l'anfiteatro della colonia romana di Luni, ben visibile dall'alto grazie alla sua forma ellittica." },
      { img: "assets/img/fossacava_tagliata.jpg", q: "Che cos'è questa grande parete di roccia?", options: ["Il fronte di una cava di marmo scavata dai romani", "Una scogliera naturale mai toccata dall'uomo"], answer: 0,
        info: "Questa è la Grande Tagliata di Fossacava, alta circa 20 metri, scavata nell'arco di secoli." },
      { img: "assets/img/lizzatura.jpg", q: "Cosa stanno facendo queste persone?", options: ["Stanno trasportando un blocco di marmo lungo il pendio", "Stanno costruendo una casa di legno"], answer: 0,
        info: "Questa tecnica di trasporto dei blocchi si chiama lizzatura ed è antichissima." },
      { img: "assets/img/busto_luni.jpg", q: "Di che materiale è fatta questa statua?", options: ["Marmo", "Legno"], answer: 0,
        info: "La statua, ritrovata a Luni, è scolpita nel pregiato marmo bianco lunense." },
      { img: "assets/img/mosaico_luni.jpg", q: "Come si chiama questa decorazione fatta di tante piccole tessere colorate?", options: ["Mosaico", "Affresco"], answer: 0,
        info: "I mosaici romani decoravano pavimenti e pareti con tessere di pietra, marmo o vetro colorato." }
    ]
  },

  medio: {
    multipla: [
      { q: "In che anno, secondo la tradizione, fu fondata Roma?", options: ["753 a.C.", "509 a.C.", "27 a.C.", "476 d.C."], answer: 0,
        info: "La data tradizionale della fondazione di Roma è il 753 a.C." },
      { q: "Come si chiama la forma di governo di Roma prima dell'Impero, guidata dal Senato e da magistrati eletti?", options: ["Monarchia", "Repubblica", "Tirannia", "Oligarchia teocratica"], answer: 1,
        info: "La Repubblica romana durò dal 509 a.C. circa fino all'ascesa di Augusto nel 27 a.C." },
      { q: "Chi sconfisse Annibale nella decisiva battaglia di Zama (202 a.C.)?", options: ["Scipione l'Africano", "Giulio Cesare", "Fabio Massimo", "Marco Antonio"], answer: 0,
        info: "La vittoria di Zama pose fine alla Seconda Guerra Punica a favore di Roma." },
      { q: "Quale fiume Giulio Cesare attraversò nel 49 a.C., dando inizio alla guerra civile?", options: ["Il Tevere", "Il Rubicone", "Il Po", "Il Volturno"], answer: 1,
        info: "'Alea iacta est' (il dado è tratto): con questa frase Cesare avrebbe commentato il gesto." },
      { q: "Chi formava, insieme ad Augusto e Marco Antonio, il Secondo Triumvirato?", options: ["Lepido", "Pompeo", "Crasso", "Bruto"], answer: 0,
        info: "Il Secondo Triumvirato (43 a.C.) univa Ottaviano, Marco Antonio e Marco Emilio Lepido." },
      { q: "In quale battaglia navale Ottaviano sconfisse Marco Antonio e Cleopatra?", options: ["Azio", "Salamina", "Canne", "Farsalo"], answer: 0,
        info: "La battaglia di Azio (31 a.C.) segnò la fine delle guerre civili e l'inizio del potere assoluto di Ottaviano." },
      { q: "Quale imperatore fece ricostruire il Pantheon nella forma che conosciamo oggi?", options: ["Adriano", "Nerone", "Costantino", "Claudio"], answer: 0,
        info: "Adriano fece ricostruire il Pantheon nel II secolo d.C. sopra un edificio precedente voluto da Agrippa." },
      { q: "Con quale editto Costantino garantì la libertà di culto ai cristiani (313 d.C.)?", options: ["Editto di Milano", "Editto di Nantes", "Editto di Roma", "Editto di Bisanzio"], answer: 0,
        info: "L'Editto di Milano pose fine alle persecuzioni contro i cristiani nell'Impero Romano." },
      { q: "Chi erano i 'conductores' nelle cave di marmo romane come Fossacava?", options: ["Imprenditori privati che gestivano l'appalto della cava", "Sacerdoti del culto della dea Luna", "Soldati a guardia della cava", "Schiavi liberati dai romani"], answer: 0,
        info: "I conductores stipulavano contratti con l'amministrazione imperiale per gestire l'estrazione del marmo." },
      { q: "Qual era il porto romano collegato alle cave di marmo apuane e alla città di Luni?", options: ["Portus Lunae", "Ostia Antica", "Portus Traiani", "Classe"], answer: 0,
        info: "Da Portus Lunae, alla foce del fiume Magra, il marmo apuano partiva verso Roma e le province." }
    ],
    vf: [
      { q: "Il Senato romano era composto esclusivamente da militari in servizio attivo.", answer: false,
        info: "Il Senato riuniva soprattutto ex magistrati ed esponenti dell'aristocrazia romana." },
      { q: "La battaglia di Canne (216 a.C.) fu una pesante sconfitta romana contro Annibale.", answer: true,
        info: "Canne è ricordata come una delle peggiori disfatte militari della storia romana." },
      { q: "Nerone apparteneva alla dinastia Giulio-Claudia.", answer: true,
        info: "Nerone fu l'ultimo imperatore della dinastia Giulio-Claudia, iniziata con Augusto." },
      { q: "La Colonna Traiana racconta a immagini la guerra di Traiano contro i Daci.", answer: true,
        info: "Il fregio a spirale della colonna narra le campagne daciche dell'imperatore Traiano." },
      { q: "Il marmo estratto a Fossacava, il bardiglio, era di colore bianco puro.", answer: false,
        info: "Il bardiglio era una varietà grigio-azzurra, ben diversa dal marmo bianco della vicina cava di Gioia." },
      { q: "Augusto affermò di aver trovato Roma di mattoni e di averla lasciata di marmo.", answer: true,
        info: "La frase, attribuita a Svetonio, sintetizza la rivoluzione edilizia augustea, sostenuta anche dal marmo di Carrara." },
      { q: "La colonia romana di Luni fu fondata nel 177 a.C.", answer: true,
        info: "Luni, con il suo porto, divenne il principale centro per l'esportazione del marmo apuano." },
      { q: "I marchi di cava (notae lapicidinarum) avevano solo valore decorativo, senza alcuna funzione amministrativa.", answer: false,
        info: "I marchi indicavano proprietà, settore di estrazione e responsabile del taglio: veri documenti amministrativi." },
      { q: "Il Colosseo fu costruito per volere dell'imperatore Vespasiano e inaugurato da Tito.", answer: true,
        info: "I lavori iniziarono sotto Vespasiano (72 d.C. circa) e l'anfiteatro fu inaugurato dal figlio Tito nell'80 d.C." },
      { q: "Le Guerre Puniche furono combattute tra Roma e la Grecia.", answer: false,
        info: "Le Guerre Puniche opposero Roma a Cartagine, potenza commerciale del Nord Africa." }
    ],
    immagine: [
      { img: "assets/img/fossacava_marchidicava.webp", q: "Cosa rappresentano queste incisioni sul blocco di marmo?", options: ["Marchi di cava (notae lapicidinarum) con informazioni sul lavoro", "Semplici graffiti senza alcun significato"], answer: 0,
        info: "Le notae lapicidinarum indicavano proprietario, settore di cava e responsabile del taglio." },
      { img: "assets/img/mappa_luni.jpg", q: "Cosa raffigura questa illustrazione?", options: ["Una ricostruzione della città romana di Luni", "Una mappa del centro di Roma antica"], answer: 0,
        info: "L'illustrazione mostra gli edifici principali di Luni: Grande Tempio, teatro, anfiteatro, domus e foro." },
      { img: "assets/img/mappa_luni_livello_del_mare.jpg", q: "Cosa mostra questa mappa satellitare?", options: ["L'antica linea di costa e il porto di Luni rispetto a oggi", "I confini dell'Impero Romano"], answer: 0,
        info: "La mappa confronta l'antica foce del Magra e il Portus Lunae con la costa attuale, molto arretrata." },
      { img: "assets/img/fossacava_cannocchiale.jpg", q: "Cosa si può osservare da questo punto panoramico?", options: ["Il paesaggio delle Alpi Apuane e la costa verso il mare", "Il centro storico di Roma"], answer: 0,
        info: "Dal belvedere di Fossacava si domina la valle delle cave fino alla costa apuana." },
      { img: "assets/img/fossacava_birdeye.jpg", q: "Cosa mostra questa vista aerea?", options: ["L'intera area della cava romana di Fossacava", "Il porto antico di Luni"], answer: 0,
        info: "Si notano il piazzale di lavorazione, le passerelle del percorso di visita e i fronti di escavazione." },
      { img: "assets/img/busto_luni.jpg", q: "Questa statua ritrae probabilmente:", options: ["Un comandante con corazza militare (paludamentum)", "Un senatore in toga civile"], answer: 0,
        info: "La corazza decorata e il mantello militare suggeriscono un personaggio di alto rango militare." },
      { img: "assets/img/labra.jpg", q: "A cosa servivano oggetti come questo labrum nell'antica Roma?", options: ["Come vasche per fontane e terme", "Come sarcofagi per le sepolture"], answer: 0,
        info: "Il bardiglio apuano era molto usato per i labra, grazie al colore che richiamava l'acqua." },
      { img: "assets/img/lizzatura.jpg", q: "Come si chiama questa tecnica tradizionale di discesa dei blocchi di marmo lungo il pendio?", options: ["Lizzatura", "Sbozzatura"], answer: 0,
        info: "La lizzatura, con corde e tronchi (piri), è una tecnica di origine antichissima ancora praticata a Carrara." }
    ]
  },

  senior: {
    multipla: [
      { q: "Quale riforma amministrativa di Diocleziano divise il potere imperiale tra quattro sovrani?", options: ["La Tetrarchia", "Il Principato", "Il Consolato perpetuo", "La Prefettura urbana"], answer: 0,
        info: "La Tetrarchia (293 d.C.) affidava il governo a due Augusti e due Cesari, per gestire meglio un Impero sempre più vasto." },
      { q: "Quale legge arcaica costituì la prima codificazione scritta del diritto romano?", options: ["Le XII Tavole", "L'Editto di Rotari", "La Lex Iulia", "Il Corpus Iuris Civilis"], answer: 0,
        info: "Le XII Tavole (V secolo a.C.) resero pubblico e scritto il diritto, prima tramandato oralmente dai patrizi." },
      { q: "Come si chiamava il percorso tipico delle cariche pubbliche a Roma, dal questore al console?", options: ["Cursus honorum", "Res publica", "Pax Romana", "Ius civile"], answer: 0,
        info: "Il cursus honorum stabiliva un ordine gerarchico e un'età minima per accedere alle magistrature." },
      { q: "In quale battaglia Publio Quintilio Varo perse tre legioni contro le tribù germaniche (9 d.C.)?", options: ["Teutoburgo", "Zama", "Farsalo", "Filippi"], answer: 0,
        info: "Il disastro di Teutoburgo convinse Roma a rinunciare all'espansione oltre il Reno." },
      { q: "Chi sconfisse Pompeo nella decisiva battaglia di Farsalo (48 a.C.)?", options: ["Giulio Cesare", "Ottaviano", "Marco Antonio", "Bruto"], answer: 0,
        info: "La vittoria di Farsalo aprì a Cesare la via al potere assoluto su Roma." },
      { q: "Quale imperatore, morto nel 235 d.C., segnò l'inizio della cosiddetta 'crisi del III secolo'?", options: ["Alessandro Severo", "Marco Aurelio", "Commodo", "Settimio Severo"], answer: 0,
        info: "Con l'assassinio di Alessandro Severo si aprì un lungo periodo di instabilità politica e militare." },
      { q: "Come si chiamavano i magistrati eletti a difesa della plebe, dotati di potere di veto?", options: ["Tribuni della plebe", "Edili curuli", "Censori", "Pretori urbani"], answer: 0,
        info: "I tribuni della plebe, istituiti dopo le prime secessioni plebee, potevano bloccare le decisioni dei magistrati patrizi." },
      { q: "Quale storico greco descrisse, nella sua Geographica, il marmo bardiglio delle cave apuane?", options: ["Strabone", "Erodoto", "Tucidide", "Plutarco"], answer: 0,
        info: "Strabone annoverò il bardiglio tra i marmi apuani di pregio esportati verso Roma." },
      { q: "Che cosa indicava la sigla 'COL' incisa sui blocchi di marmo di Fossacava?", options: ["La proprietà della Colonia di Luni", "Il nome di uno scultore", "La provincia di destinazione", "Un'unità di misura"], answer: 0,
        info: "COL (Colonia) segnalava che il blocco apparteneva alla colonia di Luni, proprietaria del fronte di cava." },
      { q: "In quale periodo si colloca l'abbandono definitivo della cava di Fossacava?", options: ["III–IV secolo d.C.", "I secolo a.C.", "VIII secolo d.C.", "Età augustea"], answer: 0,
        info: "Lo scavo stratigrafico del 2015 ha confermato l'abbandono tra III e IV secolo d.C., anche per l'esaurimento del banco marmifero." }
    ],
    vf: [
      { q: "Il Dominato instaurato da Diocleziano accentuò il carattere assoluto e sacrale del potere imperiale rispetto al Principato augusteo.", answer: true,
        info: "Con il Dominato l'imperatore ('dominus') assunse un'aura quasi divina, distante dalle forme repubblicane del Principato." },
      { q: "Le leggi Iulie promosse da Augusto includevano anche norme sul matrimonio e sulla moralità pubblica.", answer: true,
        info: "Augusto usò la legislazione anche come strumento di riforma sociale e morale." },
      { q: "La battaglia di Filippi (42 a.C.) vide la sconfitta definitiva dei cesaricidi Bruto e Cassio.", answer: true,
        info: "Ottaviano e Marco Antonio sconfissero gli uccisori di Cesare, chiudendo quella fase della guerra civile." },
      { q: "Il culto della dea Luna era estraneo alla religiosità dei cavatori delle cave apuane.", answer: false,
        info: "La dea Luna, protettrice di Luni, era una delle divinità più venerate nei siti estrattivi, insieme a Silvano." },
      { q: "Lo scavo stratigrafico di Fossacava del 2015 ha permesso di datare le fasi di sfruttamento della cava fino all'abbandono tra III e IV secolo d.C.", answer: true,
        info: "Lo scavo ha rivelato anche fasi di frequentazione medievale e moderna successive all'abbandono romano." },
      { q: "Il liberto era uno schiavo che aveva ottenuto la libertà, e talvolta assumeva ruoli di supervisione nelle cave.", answer: true,
        info: "Nella gerarchia del lavoro in cava, i liberti si collocavano spesso sopra gli schiavi, sotto i capicantiere liberi." },
      { q: "La riforma tetrarchica di Diocleziano prevedeva un solo imperatore assoluto senza colleghi.", answer: false,
        info: "La Tetrarchia divideva il potere tra due Augusti e due Cesari, proprio per evitare un accentramento unico." },
      { q: "Il senatoconsulto era una semplice raccomandazione del Senato priva di qualunque valore politico.", answer: false,
        info: "Pur non avendo forza di legge in senso stretto, il senatoconsulto aveva grande autorevolezza politica e veniva di norma rispettato." },
      { q: "Il 'pelo' del marmo, nella tecnica estrattiva romana, indicava una frattura naturale della roccia sfruttata dai cavatori per il distacco dei blocchi.", answer: true,
        info: "I cavatori sfruttavano queste fratture naturali per facilitare la separazione del blocco dal banco roccioso." },
      { q: "Il porto di Luni (Portus Lunae) perse progressivamente importanza a causa dell'interramento della foce del fiume Magra.", answer: true,
        info: "I sedimenti del Magra allontanarono nei secoli la linea di costa, rendendo il porto sempre meno praticabile." }
    ],
    immagine: [
      { img: "assets/img/fossacava_tagliata.jpg", q: "Le tracce 'a festone' visibili su questa parete derivano da:", options: ["Tagli successivi dall'alto verso il basso, ripetuti per secoli", "Un singolo evento sismico che ha spaccato la roccia"], answer: 0,
        info: "L'andamento curvilineo delle tracce nasce dalla ripetizione della tecnica di taglio a formelle, per secoli." },
      { img: "assets/img/fossacava_marchidicava.webp", q: "Il nome tecnico di queste iscrizioni funzionali è:", options: ["Notae lapicidinarum", "Tituli picti"], answer: 0,
        info: "Le notae lapicidinarum sono sigle incise a scalpello, distinte dai tituli picti (iscrizioni dipinte su altri supporti)." },
      { img: "assets/img/mappa_luni_livello_del_mare.jpg", q: "Il fenomeno geografico illustrato in questa mappa è dovuto principalmente a:", options: ["L'interramento costiero causato dai sedimenti del fiume Magra", "L'innalzamento del livello del mare in epoca romana"], answer: 0,
        info: "L'accumulo di sedimenti fluviali ha spostato la linea di costa, allontanando Luni dal mare rispetto all'antichità." },
      { img: "assets/img/busto_luni.jpg", q: "L'abbigliamento della figura (corazza e paludamentum) è tipico di:", options: ["Un comandante militare di alto rango", "Un magistrato civile in toga"], answer: 0,
        info: "Il paludamentum, mantello militare, distingueva generali e alti comandanti dai magistrati in toga civile." },
      { img: "assets/img/mappa_luni.jpg", q: "Tra gli edifici di Luni ricostruiti in questa illustrazione compaiono:", options: ["Il Grande Tempio e il teatro", "Il Colosseo"], answer: 0,
        info: "La pianta ricostruttiva mostra tempio, teatro, anfiteatro, domus e il tracciato del cardo maximus." },
      { img: "assets/img/strumenti_estrazione_marmo.jpg", q: "Quale strumento tra questi serviva a scavare la trincea perimetrale nella tecnica estrattiva romana?", options: ["Il piccone pesante", "Lo scalpello di precisione"], answer: 0,
        info: "Il piccone apriva la trincea (40-50 cm di profondità); lo scalpello serviva invece alle incisioni fini, come i marchi." },
      { img: "assets/img/anfiteatro_luni.jpg", q: "La forma ellittica di questo edificio era funzionale a:", options: ["Ospitare spettacoli di gladiatori e venationes", "Celebrare riti religiosi al chiuso"], answer: 0,
        info: "Gli anfiteatri, a pianta ellittica, garantivano visuale ottimale su combattimenti e cacce simulate (venationes)." },
      { img: "assets/img/lizzatura.jpg", q: "La tecnica di discesa dei blocchi mostrata in foto ha origini:", options: ["Antiche, riconducibili a tecniche di trasporto di tradizione romana", "Esclusivamente industriali, nate nel XX secolo"], answer: 0,
        info: "Sebbene gli strumenti si siano evoluti, il principio del trasporto a gravità su un piano inclinato ha radici antichissime." }
    ]
  }

};
